### ISSUE TITLE
Fail to get a output reading in games

### ISSUE THREAD

**Issue by joppy-at-git** [brentaro/QMK_HID_Gamepad_with_SOCD#3]
I have added Joystick support to my keyboard and replaced WASD with X and Y axis, as well as tried simple buttons suck as Cross. I get a reading in the "Game Controller Setting" found after right clicking my keyboard in "Devices and Printers". I also get a reading when using a site suck as https://gamepad-tester.com/, but I only get axis 0 and 1 or button 0 or 1, nothing like L-stick or Cross. When entering a steam the buttons or axis does not match up to anything and I can not rebind any input to them. Do I need some third party program or similar for games to recognize it as a L-stick from e.g. a Xbox controller? Or can you not combine regular keyboard keycodes such as KC_R on the same layer (or even the same keyboard) without making games and steam recognize it as a regular Xbox controller that work inside any game with controller support?

**Comment by brentaro** [comment]
Hey, those are the same outputs I receive on my end when using the gamepad tester. So I'll assume you mapped it correctly. Again, these are HID USB gamepad outputs so most programs that require xinput will not read or use these inputs. You are correct that they appear as either axis or button 0 etc.

To get it to work on steam, you have to go to settings > controller > General Controller Settings.

Make sure, Generic Gamepad support is enabled/checked on here.

Your "controller" or keyboard name should appear toward the bottom left. Clicking on it, you can see a Define Layout button where you can start to map the inputs manually.

For games outside of steam or if you do not want to use steam. You'll have to use a third party program like x360ce.

Let me know if this solves your problem.

**Comment by joppy-at-git** [comment]
I have gotten all input to work correctly with Steam through its interpretation layer. I also found out about XInput, and realized this is what I have been missing,  since I wish to be able to use it plug and play without Steam or other third party tools if I so wish. Thus I have been currently in the prosses of researching XInput implementation into QMK, sadly I have not find any fork that does this and I think it might be too hard for me to able to implement it myself. And true XInput that makes it works directly consoles and such also seem to be even harder since it requires proprietary software and hardware, and at the moment that is out of my scope. 

But thanks for the reply.

**Comment by brentaro** [comment]
Unfortunately, QMK Joystick support only deals with HID atm. Even the joystick documentation is limited. For now, I'll close this issue.
